---
title: "contabiliDados?"
#subtitle: "Todos os membros"
listing:
  - id: profs
    contents: curriculum/profs/*.qmd
    type: default
    fields: [image, date, title, subtitle, categories, author]  
    sort: "date desc"
    categories: unnumbered
    sort-ui: false
    filter-ui: false
  - id: alunos
    contents: curriculum/alunos/*.qmd
    type: default
    fields: [image, date, title, subtitle, categories, author]
    sort: "date desc"
    categories: unnumbered
    sort-ui: false
    filter-ui: false
    
page-layout: full
title-block-banner: false
toc: false
---

```{=html}
<style>
p {
    text-align: justify;
}
</style>
```
O processo de registro contábil acarreta na geração de um vasto banco de dados empresarial que pode ser usado internamente (gestores) ou externamente (investidores) para o processo decisório. O uso desses bancos de dados como fonte de informação tem sido cada vez explorado por profissionais contábeis, sendo uma nova habilidade a ser requerida para o profissional. Nesse contexto, a eficiência do processo decisório passa pela aplicação de métodos e técnicas que transformem dados brutos em informações úteis. O acesso aos dados brutos tem sido facilitados com a disseminação e ampliação do número de bancos de dados disponíveis na web. Esse projeto se direciona, portanto, na pesquisa de técnicas que otimizem o processo decisório com uso de tecnologias disponíveis.

Maiores informações:[CNPQ](https://dgp.cnpq.br/dgp/espelhogrupo/480677)

# Quem somos?

## Professores

::: {#profs}
:::

## Alunos

::: {#alunos}
:::
